name: photo_daily_app
description: This is the portfolio by Ayumu for Automation Lab.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  flutter_svg: ^0.19.3
  image_picker: ^0.7.4
  firebase_storage: ^8.0.1



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/ayumu.jpeg
    - images/ #
